# fly.toml app configuration file generated for voltray-oracle on 2026-06-13T04:13:27+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'voltray-oracle'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[[restart]]
  policy = 'always'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
